version: "3"

services:
  webapp:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - db
    ports:
      - "3003:3003"
    networks:
      - backend

  db:
    image: mongo
    restart: "always"
    volumes:
      - ./src/db_storage_docker:/usr/src/app/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
